[build]
command = "npm run build"
publish = "out/renderer"

[[redirects]]
from = "/app"
to = "/index.html"
status = 200

[[redirects]]
from = "/keyboard-shortcuts"
to = "/index.html"
status = 200

[[redirects]]
from = "/shortcuts"
to = "/index.html"
status = 200

[[redirects]]
from = "/privacy"
to = "/index.html"
status = 200

[[redirects]]
from = "/privacy-policy"
to = "/index.html"
status = 200
